"""add day_name to work_days

Revision ID: c2e280294871
Revises: 251d14963e9c
Create Date: 2025-06-25 23:59:18.778286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e280294871'
down_revision: Union[str, Sequence[str], None] = '251d14963e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_days', sa.Column('day_name', sa.String(length=9), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_days', 'day_name')
    # ### end Alembic commands ###
