name: EC2 Direct Deploy

on:
  push:
    branches: [main]      # deploy only from main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (needed only to satisfy actions/checkout)
        uses: actions/checkout@v4


      - name: Debug secret
        run: echo "Host is ${{ secrets.EC2_SSH_HOST }}"
      - name: Debug secret 2
        run: echo "App DIR is ${{ secrets.EC2_APP_DIR }}"



      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "▶ 1) Navigate to app dir"
            cd ${{ secrets.EC2_APP_DIR }}

            echo "▶ 2) Pull latest code"
            git fetch origin main && git reset --hard origin/main

            echo "▶ 3) Stop & remove old container"
            docker stop attendance-tracker || true
            docker rm   attendance-tracker || true

            echo "▶ 4) Remove old image"
            docker rmi attendance-tracker || true

            echo "▶ 5) Build new image"
            docker build -t attendance-tracker .

            echo "▶ 6) Start container"
            docker run -d \
              --restart unless-stopped \
              --env-file ${{ secrets.ENV_PATH }} \
              -p 8000:8000 \
              --name attendance-tracker \
              attendance-tracker